export const roles = {
   background: { dark: "neutral6", light: "neutral98" },
   error: { dark: "error80", light: "error40" },
   "error-container": { dark: "error30", light: "error90" },
   "inverse-on-surface": { dark: "neutral20", light: "neutral95" },
   "inverse-primary": { dark: "primary40", light: "primary80" },
   "inverse-surface": { dark: "neutral90", light: "neutral20" },
   "on-background": { dark: "neutral90", light: "neutral10" },
   "on-error": { dark: "error20", light: "error100" },
   "on-error-container": { dark: "error90", light: "error10" },
   "on-primary": { dark: "primary20", light: "primary100" },
   "on-primary-container": { dark: "primary90", light: "primary10" },
   "on-primary-fixed": { dark: "primary10", light: "primary10" },
   "on-primary-fixed-variant": { dark: "primary30", light: "primary30" },
   "on-secondary": { dark: "secondary20", light: "secondary100" },
   "on-secondary-container": { dark: "secondary90", light: "secondary10" },
   "on-secondary-fixed": { dark: "secondary10", light: "secondary10" },
   "on-secondary-fixed-variant": { dark: "secondary30", light: "secondary30" },
   "on-surface": { dark: "neutral90", light: "neutral10" },
   "on-surface-variant": {
      dark: "neutral-variant80",
      light: "neutral-variant30",
   },
   "on-tertiary": { dark: "tertiary20", light: "tertiary100" },
   "on-tertiary-container": { dark: "tertiary90", light: "tertiary10" },
   "on-tertiary-fixed": { dark: "tertiary10", light: "tertiary10" },
   "on-tertiary-fixed-variant": { dark: "tertiary30", light: "tertiary30" },
   outline: { dark: "neutral-variant60", light: "neutral-variant50" },
   "outline-variant": { dark: "neutral-variant30", light: "neutral-variant80" },
   primary: { dark: "primary80", light: "primary40" },
   "primary-container": { dark: "primary30", light: "primary90" },
   "primary-fixed": { dark: "primary90", light: "primary90" },
   "primary-fixed-dim": { dark: "primary80", light: "primary80" },
   scrim: { dark: "neutral0", light: "neutral0" },
   secondary: { dark: "secondary80", light: "secondary40" },
   "secondary-container": { dark: "secondary30", light: "secondary90" },
   "secondary-fixed": { dark: "secondary90", light: "secondary90" },
   "secondary-fixed-dim": { dark: "secondary80", light: "secondary80" },
   shadow: { dark: "neutral0", light: "neutral0" },
   surface: { dark: "neutral6", light: "neutral98" },
   "surface-bright": { dark: "neutral24", light: "neutral98" },
   "surface-container": { dark: "neutral12", light: "neutral94" },
   "surface-container-high": { dark: "neutral17", light: "neutral92" },
   "surface-container-highest": { dark: "neutral22", light: "neutral90" },
   "surface-container-low": { dark: "neutral10", light: "neutral96" },
   "surface-container-lowest": { dark: "neutral4", light: "neutral100" },
   "surface-dim": { dark: "neutral6", light: "neutral87" },
   "surface-tint": { dark: "primary80", light: "primary40" },
   "surface-variant": { dark: "neutral-variant30", light: "neutral-variant90" },
   tertiary: { dark: "tertiary80", light: "tertiary40" },
   "tertiary-container": { dark: "tertiary30", light: "tertiary90" },
   "tertiary-fixed": { dark: "tertiary90", light: "tertiary90" },
   "tertiary-fixed-dim": { dark: "tertiary80", light: "tertiary80" },
};

export const shortFormWord = {
   background: "bg",
   error: "err",
   container: "con",
   inverse: "iv",
   surface: "sf",
   primary: "pr",
   secondary: "sec",
   fixed: "fx",
   variant: "var",
   tertiary: "ter",
   high: "hg",
   highest: "hgest",
   low: "lw",
   lowest: "lwest",
};
export const tones = [
   0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95,
   96, 98, 99, 100,
];
